name: Sahra Ghalebikesabi
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

plugins:
    - jekyll-seo-tag

theme: jekyll-theme-cayman

# Jekyll SEO tag respects any of the following
google_site_verification
